env_list = ["3.10", "3.11", "3.12" ,"3.13", "3.14", "docs"]

[env_run_base]
description = "run the test suite with pytest"
deps = [ "pytest", "coverage" ]
commands = [["coverage", "run", "-p", "-m", "pytest", { replace = "posargs", default = ["tests"], extend = true }]]

[env.docs]
description = "build documentation with sphinx"
deps = [ "sphinx", "sphinx-markdown-builder==0.6.10" ]
commands = [["sphinx-build", "-M", "markdown", "docs/source", "docs/build", ]]

[env.mypy]
description = "run mypy to typecheck and lint"
deps = [ "mypy", "pytest" ]
commands = [["mypy", "." ]]

[env.isort]
description = "run isort to alphabetize imports"
deps = [ "isort" ]
commands = [["isort", "-c", "." ]]

[env.black]
description = "run black to check formatting"
deps = [ "black" ]
commands = [["black", "--check", "." ]]
